#! /bin/sh

ps cax | grep sxhkd > /dev/null
if [ $? -eq 0 ]; then
	pkill -USR1 -x sxhkd
else
	sxhkd &
fi

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 1 2 3 4 5 6 7 8 9 0 
~/.config/bspwm/populate-monitors.sh
#bspc monitor -d 1
# CHECK IF WORKS ^^^^

# New windows on the left
bspc config initial_polarity second_child

bspc config border_width         	3
bspc config window_gap          	12

bspc config split_ratio          	0.50
bspc config pointer_follows_monitor true

#
# Autostart
#
# Launch Compton
compton &

# Launch Polybar
$HOME/.config/polybar/launch.sh

# Launch Feh
feh --bg-fill $HOME/.config/bspwm/wallpaper.jpg

# Numlock
numlockx on

# Keyboard layouts
setxkbmap -layout us,lt,ru -option 'grp:alt_space_toggle' -option caps:escape

# Key repeat rate
xset r rate 300 60

# Disable beeping
xset b off

# Fix cursor
xsetroot -cursor_name left_ptr

# Subscriptions
$HOME/.config/bspwm/subscriptions.sh

# Floating rules
	# Clear past rules
	bspc rule -r *:*
bspc rule -a URxvt:urxvtfloat state=floating
bspc rule -a love state=floating
bspc rule -a Soffice state=tiled
bspc rule -a *:zathura state=tiled
#bspc rule -a LibreOffice state=floating
#bspc rule -a libreoffice state=tiled

# ^^^ Makes the dialog boxes also tiled

# Defaults Probably need to be removed
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc config borderless_monocle   true
bspc config gapless_monocle      true
